### ISSUE TITLE
Attack and Release times do not work

### ISSUE THREAD

**Issue by erk1313** [Tympan/Tympan_Sandbox#4]
The attack and release times for per-band expansion have no effect.
- I verified that expansion is being applied (compare to when expansion was disabled by setting the ratio to 1.0).  However, when I first power up the Tympan, with the attack time set high (5000ms), expansion is not delayed.
  
<img src = "https://user-images.githubusercontent.com/68314730/90680204-802d1580-e22f-11ea-831c-0566e1fe1814.png" height =200/>

**Comment by erk1313** [comment]
@chipaudette As we talked about a few months ago, the attack and release times do not seem to delay when expansion is applied.  Thought I would add this as an issue so it can be addressed later.

**Comment by wheresaddie** [comment]
@biomurph

**Comment by biomurph** [comment]
@wheresaddie Hi! You ping me?
This issue appears to be purely in software. While I'm intimate with some of the ins-and-outs, I don't know much about attack and release... Is there some way I can be of assistance in this?

**Comment by chipaudette** [comment]
@erk1313 

The graph that you produced isn't really helping me see the problem.  As the attack and release times alter the time-response of the system, we really need to see a time-based graph to confirm that there is a problem and to see what the problem might be.  So, a more helpful graph might be regular time plot of the output waveform for a known input waveform.

As an example, from my blog post: http://openaudio.blogspot.com/2017/01/basic-dynamic-range-compressor.html

![Results-Steps](https://user-images.githubusercontent.com/1806494/90778564-c84d4600-e2ca-11ea-9a40-c4d752c7f6af.png)

In this case, you might try something like:

* Set the expansion threshold to be a relatively high SPL value so that you can easily work within the expansion regime.  
* Inject (or synthesize) a sine wave at a fixed frequency.  Set the amplitude to be solidly within the expansion regime.  
* At some point, induce a step change in amplitude (up or down) of the sine wave, but make sure that the amplitude is still within the expansion regime.  
* At a later point, induce a step change back to the original value.
* Throughout the test, record the output signal (to SD card or whatever).
* Bring over to your PC and plot the output waveform.  
* Repeat with other attack and release times

When looking at the output waveform, the step change in the input amplitude ought to be replaced with a smoothly changing output amplitude.  Changing the attack time ought to affect how long it takes to respond to an upward change in amplitude.  Changing the release time ought to affect its response to a downward change in amplitude.  

The plots from my blog post were for compression, not expansion.  So, your plots (being a study of the expansion regime) will look different.  But, it still ought to be obvious that it is doing something.  And, it still ought to be affected by the attack or release.

Chip

**Comment by erk1313** [comment]
### Using Amplitude Sweep to Demonstrate Expansion (check!)
* Input Tone: 1kHz Amplitude sweep from -54dB FS to -3dB FS (76dB SPL to 127dB SPL).

Expansion Settings: 
* Expansion Ratio: 0.5
* Expansion Knee: 100dB SPL
* Expansion Attack;Release: 5ms; 300ms
* Compression Start Gain: 0dB SPL
* Max dB: 130dB SPL (scales the dB FS to dB SPL) 

**Time Series**
<img src = "https://user-images.githubusercontent.com/68314730/91675617-ffadc500-eb0a-11ea-8f52-2b5cf7263ee1.png" height = 300/>

**Output/Input**
<img src = "https://user-images.githubusercontent.com/68314730/91675080-0cc9b480-eb09-11ea-9e95-b5d5ede6fd4e.png"  height = 300/>

Expansion occurs at the specified kneepoint (100dB SPL) with the expected expansion ratio of 0.5
* Change in input: 99dB SPL - 79 dB SPL = 20dB
* Change in output: 99dB SPL - 59dB SPL = 40dB
Expansion Ratio: 20dB/40dB = 0.5

**Comment by erk1313** [comment]
### Demonstrating Attack and Release Time for Expansion (check!)
* Input Tone: 1kHz tone alternating between -40dB FS and -20dBFS (90dB SPL and 110dB SPL)

Expansion Settings: 
* Expansion Ratio: 0.5
* Expansion Knee: 100dB SPL
* Expansion Attack; Release: **500ms; 500ms**
* Compression Start Gain: 0dB SPL
* Max dB: 130dB SPL (scales the dB FS to dB SPL) 

**Time Series**
<img src = "https://user-images.githubusercontent.com/68314730/91678558-dcd3de80-eb13-11ea-9824-49ad11dd769c.png" height =200/>

**Gain Over Time**
<img src = "https://user-images.githubusercontent.com/68314730/91680038-00992380-eb18-11ea-921e-0488d8fbca0b.png" height =400/>

Gain Out of Expansion: -8dB
Gain In Expansion: -28dB 

**Attack and Release Time**
Attack Time (within 2dB of gain in expansion): 200ms
Release Time (within 2dB of gain out of expansion): 220ms 

Note that attack and release time was defined according to a random [paper ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4172289/#:~:text=Otherwise%2C%20no%20gain%20reduction%20occurs,is%20called%20the%20attack%20time.)I found. Otherwise I think it is reasonable to assume the 500ms attack and release time are working as they should.

**Comment by erk1313** [comment]
For completeness...
### Demonstrating Compression during Amplitude Sweep (check!)
Input Tone: 1kHz Amplitude sweep from -54dB FS to -3dB FS (76dB SPL to 127dB SPL).
Expansion Settings:

Compression Start Gain: 0dB SPL
Compression Ratio: 1.5
Compression Knee: 100dB SPL
Attack;Release: 5ms; 5ms
Max dB: 130dB SPL (scales the dB FS to dB SPL)
Limiter: 200dB SPL

**Time-Series**
<img src ="https://user-images.githubusercontent.com/68314730/91682051-48bb4480-eb1e-11ea-870b-20b4170746f3.png" height =200/>


**Output-Input Gain**
<img src = "https://user-images.githubusercontent.com/68314730/91681796-8e2b4200-eb1d-11ea-94d6-4fb904aba64d.png" height =400/>

The compression knee occurred at 107dB SPL, a little higher than the expected 100dB SPL.
Expansion ratio measured 1.4, close to the expected 1.5

Change in input: 115.5dB SPL - 108.5dB SPL = 7dB
Change in output: 114.1dB SPL - 109.1dB SPL = 5dB
Compression Ratio: (7dB/5dB) = 1.4

**Comment by erk1313** [comment]
Everything checks out: Expansion and Compression work as expected, with attack and release time verified for the case of expansion.
