### ISSUE TITLE
nRF52840 Serial Baud Rate Test

### ISSUE THREAD

**Issue by biomurph** [Tympan/Tympan_Sandbox#6]
@chipaudette 
Two sketches in the biomurph branch of this repo work together to benchmark the serial baud rate between Teensy and nRF52840 on the Tympan Rev F.

- [nRF52840_SerialEcho.ino](https://github.com/Tympan/Tympan_Sandbox/tree/biomurph/Tympan%20Bluetooth/nRF52840%20Firmware/Baud_Rate_Testing/nRF52840_SerialEcho)
- [Tympan_SerialEcho.ino](https://github.com/Tympan/Tympan_Sandbox/tree/biomurph/Tympan%20Bluetooth/nRF52840%20Firmware/Baud_Rate_Testing/Tympan_SerialEcho)

In this test, the nRF52 sends 256 bytes to the Teensy. 
Teensy uses a manual serial data collection scheme that buffers the incoming stream until  a '\n' (newline) is read on the port.
The nRF52 code is written to always terminate the data stream with a newline character.
The following output on the serial monitor running Tympan_SerialEcho.ino will look like this when you run it and send 't' over the USB UART.

The Tympan reports the number of bytes received from the nRF52.
nRF52 sends it's byte counter after sending the data buffer.

```
Tympan Serial Echo: starting...
Tympan Help:
    : h : print this help
    : All characters (including 'h') are sent to BLE
Serial7 baud rate: 230400
Tympan sending to nRF: t
Tympan Received 28 bytes from nRF
nRF52840 Serial1 Received: t
Tympan Received 256 bytes from nRF
0123456701234567012345670123456701234567012345670123456701234567012345670123456701234567012345670123456701234567012345670123456701234567012345670123456701234567012345670123456701234567012345670123456701234567012345670123456701234567012345670123456701234567
Tympan Received 34 bytes from nRF
nRF52840 uartOutBufferCounter: 256
```

Successful test has been run up to 230400 baud.
Check the comments in the code for functionality. Maintain agreement on the value of nRF_UART_BAUD to ensure clear communication when testing different values.

**Comment by chipaudette** [comment]
Thanks for this code.  So helpful!

After going back and forth between you working code and my failing code, I think that I've found that it's entirely down to my Tympan code not servicing its `Serial7.read()` fast enough.  I was overflowing whatever read buffer the Teensy firmware pre-allocates for Serial7.

 - When I take my code that fails at 115200 (and higher) and replace the `delay(10)` with `delay(1)`, the system begins to work fine because now it doesn't wait around so long that the buffer overflows.

- Similarly, when I take my code that fails at 115200 and add a Teensy function call to increase the UART rx buffer size, the system begins to work fine.

So, with the problem being clearly identified as a rx buffer overrun, it's easy to fix the problem.  I can simply do what you did, which is not use the silly `delay` approach.  Great.

The bigger issue is that buffer overflow might still happen, especially for the Tympan-to-nRF communication where the nRF might not be able to echo the bytes out through the BLE link to keep up with an onslaught of bytes coming via UART from the Tympan.  This is a likely scenario as some of the GUIs descriptions that we'll be passing to the phone are very, very large.

- We could increase the UART RX buffer on the nRF.  That would probably work fine, though it does allow the Tympan to think all the bytes have been transmitted when, in fact, they're still being spooled out via the (somewhat slow) BLE link.

- Alternatively, we could enable hardware flow control (RTS/CTS) on the UART link.  This is the best solution.  I think that both devices support it, but (sadly) Adafruit doesn't expose an easy-to-call function for setting the RTS/CTS pins on Serial1.  Instead, we'll need instantiate our own instance of the UART class, which Adafruit makes easy to do.

I can't test this idea right now (and I'm off to Colorado for my brother's baby shower!) but I'll try to test this idea next week. 

Good progress, Joel.  Thanks!


When I use my version of the code (which fails at 115200 and above) but use the Teensy function calls to provide a larger receive buffer, everything works fine.  So, yeah, 

As you noticed, my method of stalling (via `delay(10)`) in order to wait for the end of not-quite-complete message

**Comment by biomurph** [comment]
It's always better not to delay, if you can avoid it.
In my code, I am not using any while() function to collect the bytes. Just once per loop, I look to see if there is anything available and save it until I come across the '\n' character. 

It seems like all of the data that you are hoping to get through the Teensy - nRF - phoneApp pipeline is in JSON format, is that correct? 

I think it could be pretty simple to set up some code to benchmark the BLE transmission. Is the Tympan app already using BLE UART for data transfer?

The other thing is just to try it and see what happens.

BTW, I am currently using the nRF52 prototype board that I made along with a Teensy 4.1 in order to speed up development.
It should be easy to drop the working code onto our Rev F systems when we have something to test.

**Comment by chipaudette** [comment]
>> In my code, I am not using any while() function to collect the bytes. Just once per loop, I look to see if there is anything available and save it until I come across the '\n' character.

Yes, I noticed that.  In playing around with what made the difference, that particular element wasn't the crucial bit (in my testing).  In my testing, the critical bit was the overflow that happened while the Teensy was forced to sit and do nothing during the `delay()`.  Getting rid of or shortening the `delay` is what caused the night-and-day difference.

>> It seems like all of the data that you are hoping to get through the Teensy - nRF - phoneApp pipeline is in JSON format, is that correct?

It is true that the giant packet of data for the GUI will be in JSON, but more generally it could be in any format.  For example, I'm still hoping that we can figure out how to get the nRF unit to run both the service ID that the Tympan_Remote app needs *and* the Adafruit UART service.  If so, that opens up more hacking opportunities for folks.  If that happens, who knows what format people will use.  So, I'm hoping to NOT tailor any optimizations for JSON, if it can be easily avoided.

>> BTW, I am currently using the nRF52 prototype board that I made along with a Teensy 4.1 in order to speed up development.  It should be easy to drop the working code onto our Rev F systems when we have something to test.

All of my recent testing has been on the Rev F so, yes!, it is easy to drop the working code on the Rev F.  It's sad, though, when I get a bug in the nRF firmware that ends up preventing OTA updates.   It means that I have to wait to go back up to Creare to use the programming nest.  Mildly annoying.

**Comment by biomurph** [comment]
Oh, if there is a bug in the firmware that prevents OTA updates, please start another issue so that it can be tracked down?

When you way you want to run the service that Tympan expects to see, I thought you had found those API tools. Did you?
I can help track that down too!

**Comment by chipaudette** [comment]
No bugs in your part...I produce bugs as I try new things, such as to enable RTS/CTS.  In the case of CTS/RTS, I don't know why my error stopped OTA, but it did.  I'm assuming that when I fix my bug, OTA will return.

As for getting the nRF to advertise the right service for the Tympan app, yes, I have that working.  No problem Or, I can have the nRF advertise the Adafruit UART service.  I can't seem to have the unit offer both.  That's the part that I'm hoping to overcome...offering both services.  Either offering literally at the same time or having them be selectable from the Tympan by sending a command from the Tympan to the nRF.  I'm guessing that the latter will end up being easier for me to figure out than the former.

Chip

**Comment by biomurph** [comment]
Which code base are you working with?

**Comment by chipaudette** [comment]
We seem to have settled this.  In V0.2.4, we're defaulting to 115200.

Closing.
